cms/src/Entity/Tasks.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TasksRepository")
 */
class Tasks
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Employee_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Client_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $End;

    /**
     * @ORM\Column(type="bigint")
     */
    private $Break;

    /**
     * @ORM\Column(type="text")
     */
    private $Activities;

    /**
     * @ORM\Column(type="text")
     */
    private $Materials;

    /**
     * @ORM\Column(type="integer")
         */
    private $Company_id;

    /**
     * @ORM\Column(type="bigint")
     */
    private $Traveldistance;

    /**
     * @ORM\Column(type="bigint")
     */
    private $date_diff;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Currentday;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmployeeId(): ?int
    {
        return $this->Employee_id;
    }

    public function setEmployeeId(int $Employee_id): self
    {
        $this->Employee_id = $Employee_id;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->Client_id;
    }

    public function setClientId(int $Client_id): self
    {
        $this->Client_id = $Client_id;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->Start;
    }

    public function setStart(\DateTimeInterface $Start): self
    {
        $this->Start = $Start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->End;
    }

    public function setEnd(\DateTimeInterface $End): self
    {
        $this->End = $End;

        return $this;
    }

    public function getBreak(): ?string
    {
        return $this->Break;
    }

    public function setBreak(string $Break): self
    {
        $this->Break = $Break;

        return $this;
    }

    public function getActivities(): ?string
    {
        return $this->Activities;
    }

    public function setActivities(string $Activities): self
    {
        $this->Activities = $Activities;

        return $this;
    }

    public function getMaterials(): ?string
    {
        return $this->Materials;

    }

    public function setMaterials(string $Materials): self
    {
        $this->Materials = $Materials;

        return $this;
    }

    public function getCompanyId(): ?int
    {
        return $this->Company_id;
    }

    public function setCompanyId(int $Company_id): self
    {
        $this->Company_id = $Company_id;

        return $this;
    }

    public function getTraveldistance(): ?string
    {
        return $this->Traveldistance;
    }

    public function setTraveldistance(string $Traveldistance): self
    {
        $this->Traveldistance = $Traveldistance;

        return $this;
    }

    public function getDateDiff(): ?string
    {
        return $this->date_diff;
    }

    public function setDateDiff(string $date_diff): self
    {
        $this->date_diff = $date_diff;

        return $this;
    }

    public function getCurrentday(): ?string
    {
        return $this->Currentday;
    }

    public function setCurrentday(string $Currentday): self
    {
        $this->Currentday = $Currentday;

        return $this;
    }
}

cms/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"Name"}, message="There is already an account with this Name")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Function;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Position = 'User';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Cost = 0 ;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /**
     * @ORM\Column(type="integer", nullable=true ,options={"default" : 15})
     */
    private $hourrate;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default" : true})
     */
    private $active;

    /**
     * @ORM\Column(type="integer",nullable=true, options={"default" : 1})
     */
    private $Transportrate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getFunction(): ?string
    {
        return $this->Function;
    }

    public function setFunction(string $Function): self
    {
        $this->Function = $Function;
        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->Position;
    }

    public function setPosition(string $Position): self
    {
        $this->Position = $Position;

        return $this;
    }

    public function getCost(): ?string
    {
        return $this->Cost;
    }

    public function setCost(string $Cost): self
    {
        $this->Cost = $Cost;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return string[] The user roles
     */
    public function getRoles()
    {
        // TODO: Implement getRoles() method.
        return array('User', 'Admin');
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return (string) $this->Password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return (string) $this->Name;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getHourrate(): ?int
    {
        return $this->hourrate;
    }

    public function setHourrate(?int $hourrate): self
    {
        $this->hourrate = $hourrate;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getTransportrate(): ?int
    {
        return $this->Transportrate;
    }

    public function setTransportrate(int $Transportrate): self
    {
        $this->Transportrate = $Transportrate;

        return $this;
    }
}

cms/templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}
{% block body %}

<header>
    <nav>
        <ul>
        {% if state != "anon."%}
            {% if state.function == "Owner"%}
                <li><a href="/">Home</a></li>
                <li><a href="/users">Users</a></li>
                <li><a href="/tasks">Tasks</a></li>
                <li><a href="/hourrates">Hourrates</a></li>
                <li><a href="/transportrates">Transportrates</a></li>
                <li><a href="/logout">Logout</a></li>
            {%elseif state.function == "Client"%}
                <li><a href="/">Home</a></li>
                <li><a href="/tasks/client/{{state.id}}">Tasks</a></li>
                <li><a href="/logout">Logout</a></li>
            {% else %}
                <li><a href="/">Home</a></li>
                <li><a href="/logout">Logout</a></li>
            {%endif%}
         {%else%}
            <li><a href="/">Home</a></li>
            <li><a href="/login">Login</a></li>
         {%endif%}
        </ul>
    </nav>
</header>
    {% if state != "anon." %}
        <div id="leftDiv">
            {% if state.function == "Client" %}
                <p> Ontvang een mail met een periode van de door u opgegeven aantal dagen</p>
                {{ form_start(form) }}
                {{ form_end(form) }}
                <p> Ontvang een pdf met een periode van de door u opgegeven aantal dagen</p>
                {{ form_start(formpdf) }}
                {{ form_end(formpdf) }}
            {% endif %}
            {% if state.function == "Owner" %}
            <h1>Most recent Users</h1>
               {% for user in recentUsers %}
                        <div id="recentusers">
                            <h2>Name: {{ user.name }}</h2>
                            <h4>Email: {{ user.email }}</h4>
                            <p>Tel: {{ user.tel }}</p>
                            
                        </div>    
                {% endfor %}
            {% endif %}
        </div>  
        <div id="middleDiv"><h1>Welkom 
            {{state.Name}}</h1>
            {% if state.function == "Employee" or state.function == "Freelance"%}
                <p> Als werknemer en/of freelancer moet u gebruik maken van onze company app om taken toe te kunnen voegen.</p>
            {% endif %}
        </div>
        <div id="rightDiv">
            {% if state.function == "Client" %}
                    <h2>Your recent tasks <a href="tasks/client/{{state.id}}">see all</a></h2>
                    <hr>
                    {% for task in cientTasks %}
                        <div id="clientTasks">
                            <h4>Employee: {{ task.EmployeeId }}</h4>
                            <p>From: {{ task.start|date('Y-m-d H:i:s')  }} Until: {{ task.end|date('Y-m-d H:i:s')  }}</p>
                            <p> </p>
                            <p>Activities: {{ task.activities }}</p>
                            <p>Materials: {{ task.materials }}</p>
                            <p>Traveldistance: {{ task.traveldistance }}km Gewerkte uren: {{ task.datediff }}uur</p>
                        </div>
                        <hr>
                {% endfor %}
            {% endif %}
            {% if state.function == "Owner" %}
                    <h1>Most recent Tasks</h1>
                    {% for task in recentTasks %}
                        <div id="recentTasks">
                            <h2>Employee: {{ task.EmployeeId }}</h2>
                            <p>Activities: {{ task.activities }}</p>
                            <p>Materials: {{ task.materials }}</p>

                        </div>
                {% endfor %}
            {% endif %}
        </div>
    {% else %}
        <div id="leftDiv">
        </div>  
        <div id="middleDiv">
        <h1>Welkom </h1>
        <p>Om gebruik te maken van onze website gelieve in te loggen.</p>
        <p>Deze website is bestemd voor de klanten van ARTE-TECH om hun taken op te volgen</p>
        <p> Bent u een werknemer en/of freelancer gelieve gebruik te maken van onze app</p>
        </div>
        <div id="rightDiv"></div>
    {% endif%}

{% endblock %}