cms/src/Entity/Hourrate.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HourrateRepository")
 */
class Hourrate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal")
     */
    private $Price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $User_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->User_id;
    }

    public function setUserId(int $User_id): self
    {
        $this->User_id = $User_id;

        return $this;
    }
}

cms/src/Controller/HourrateController.php
<?php

namespace App\Controller;

use App\Entity\Hourrate;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class HourrateController extends AbstractController
{
    /**
     * @Route("/hourrates", name="hourrate")
     */
    public function index(TokenStorageInterface $tokenStorage)
    {
        $usr = $tokenStorage->getToken()->getUser();
        if($usr =='anon.'){
           return $this->redirect('/login');
        }else{
            if($usr->getPosition() =='Admin'){
                
            }else{
                return $this->redirect('/');
            }
        }
        $repository = $this->getDoctrine()->getRepository(Hourrate::class);
        $hourrates = $repository->findBy(
            array(),
            array('Price' => 'ASC')
        );
        return $this->render('hourrate/index.html.twig', [
            'controller_name' => 'HourrateController',
            'rates' => $hourrates,
        ]);
    }
     /**
     * @Route("/edit-hourrate/{id}", name="edit-hourrate")
     */
    public function edit($id, TokenStorageInterface $tokenStorage, Request $request)
    {
        $usr = $tokenStorage->getToken()->getUser();
        if($usr =='anon.'){
           return $this->redirect('/login');
        }else{
            if($usr->getPosition() =='Admin'){
                
            }else{
                return $this->redirect('/');
            }
        }
        $manager = $this->getDoctrine()->getManager();
        $rate = $manager->getRepository(Hourrate::class)->find($id);
        $form = $this->createFormBuilder($rate)
        ->add('Price', TextType::class)
        ->add('Submit', SubmitType::class)
        ->getForm();
        if ($request->getMethod() == 'POST') {
            $data = $request->request->get('form');
            $rate->setPrice($data['Price']);
            $manager->flush();
            return $this->redirectToRoute('hourrates');

        }
        return $this->render('hourrate/edit.html.twig', [
            'controller_name' => 'HourrateController',
            'form' => $form->createView(),
        ]);
    }
     /**
     * @Route("/add-hourrate", name="add-hourrate")
     */
    public function add(TokenStorageInterface $tokenStorage, Request $request)
    {
        $usr = $tokenStorage->getToken()->getUser();
        if($usr =='anon.'){
           return $this->redirect('/login');
        }else{
            if($usr->getPosition() =='Admin'){
                
            }else{
                return $this->redirect('/');
            }
        }
        $rate = new Hourrate();
        $form = $this->createFormBuilder($rate)
        ->add('Price', TextType::class)
        ->add('Submit', SubmitType::class)
        ->getForm();
        if ($request->getMethod() == 'POST') {
            $manager = $this->getDoctrine()->getManager();
            $data = $request->request->get('form');
            // Need to do something with the data here
            $rate->setPrice($data['Price']);
            $manager->persist($rate);
            $manager->flush();
            return $this->redirectToRoute('hourrates');

        }
        return $this->render('hourrate/add.html.twig', [
            'controller_name' => 'HourrateController',
            'form' => $form->createView(),  
        ]);
    }
     /**
     * @Route("/delete-hourrate/{id}", name="delete-hourrate")
     */
    public function delete($id, TokenStorageInterface $tokenStorage)
    {
        $usr = $tokenStorage->getToken()->getUser();
        if($usr =='anon.'){
           return $this->redirect('/login');
        }else{
            if($usr->getPosition() =='Admin'){
                
            }else{
                return $this->redirect('/');
            }
        }
        $manager = $this->getDoctrine()->getManager();
        $rate = $manager->getRepository(Hourrate::class)->find($id);
        $manager->remove($rate);
        $manager->flush();
        return $this->redirectToRoute('hourrates');
    }
}

cms/templates/hourrate/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Hourrate{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
    <header>
        <nav>
            <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/users">Users</a></li>
            <li><a href="/tasks">Tasks</a></li>
            <li><a href="/hourrates">Hourrates</a></li>
            <li><a href="/transportrates">Transportrates</a></li>
            <li><a href="/logout">Logout</a></li>
            </ul>
        </nav>
    </header>
    {{ form_start(form) }}
        {{ form_row(form.Price) }}
    {{ form_end(form) }}

{% endblock %}

cms/templates/hourrate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
        <header>
    <nav>
        <ul>
       <li><a href="/">Home</a></li>
            <li><a href="/users">Users</a></li>
            <li><a href="/tasks">Tasks</a></li>
            <li><a href="/hourrates">Hourrates</a></li>
            <li><a href="/transportrates">Transportrates</a></li>
            <li><a href="/logout">Logout</a></li>
        </ul>
    </nav>
</header>    
    {{ form_start(form) }}
    {{ form_end(form) }}

{% endblock %}

cms/templates/hourrate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HourrateController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

  <header>
    <nav>
        <ul>
        <li><a href="/">Home</a></li>
            <li><a href="/users">Users</a></li>
            <li><a href="/tasks">Tasks</a></li>
            <li><a href="/hourrates">Hourrates</a></li>
            <li><a href="/transportrates">Transportrates</a></li>
            <li><a href="/logout">Logout</a></li>
        </ul>
    </nav>
</header>
<div id="container">
<a href="add-hourrate" id="add-button"> Add </a>

   <table >
    <tr>
        <th>Price</th>
    </tr>
    {% for rate in rates %}
        <tr>
            <td>{{ rate.price }}</td>
            <td><a id="edit" href="/edit-hourrate/{{rate.Id}}">Edit</a></td>
            <td> <a id="delete" href="/delete-transport/{{rate.Id}}">delete</a></td>
        </tr>
    {% endfor %}
</table>
</div>
{% endblock %}